#!/bin/sh
module="acc"
device="acc"
mode="664"

if [ "$(id -u)" != "0" ]
then
  echo "You must be root to load or unload kernel modules"
  exit 1
fi

# remove stale nodes
rm -f /dev/${device}? 

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod -f /modules/$module.ko $* || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/${device}0 c $major 0

#ln -sf ${device}0  /dev/${device}

# give appropriate group/permissions
chmod $mode  /dev/${device}[0]
 
