
test_accesso_memoria:
	@ or32-linux-gcc -o test_accesso_memoria test_accesso_memoria.c
	@ echo "GEN test_accesso_memoria"

all: test_accesso_memoria

clean: 
	@ rm -f *.o
	@ rm -f test_accesso_memoria
	@ echo "CLEAN prove"
